
version: 2.1

workflows:
  build:
    jobs:
      - build
jobs:      
  build:
    working_directory: ~/udacity-monolith-to-microservices-project
    docker:
      - image: cimg/base:2023.09
      - image: cimg/node:16.20.2
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:    
          name: build
          command: |
            # Build
              echo 'START BUILDING'
              docker build -t udagram-api-feed ./udagram-api-feed 
              docker build -t udagram-api-user ./udagram-api-user 
              docker build -t udagram-frontend ./udagram-frontend 
              docker build -t reverseproxy ./udagram-reverseproxy

            # Tagging
              echo 'START TAGGING'
              docker tag udagram-api-feed duydn97/udagram-api-feed:v1 
              docker tag udagram-api-user duydn97/udagram-api-user:v1 
              docker tag udagram-frontend duydn97/udagram-frontend:v1 
              docker tag reverseproxy duydn97/reverseproxy:v1

              echo 'DOCKER IMAGE LS'
              docker image ls
              
      - run:
          name: after_success
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push duydn97/udagram-api-feed:v1
            docker push duydn97/udagram-api-user:v1 
            docker push duydn97/udagram-frontend:v1 
            docker push duydn97/reverseproxy:v1